In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('../artifacts/sentiment_analysis.csv')

In [3]:
data.head()

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

### Data Preprocessing

In [6]:
data.shape

(7920, 3)

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
data.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

### Text Preprocessing

In [13]:
import re
import string

Convert uppercase to lowercase

In [16]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [19]:
data["tweet"].head(5)

0    #fingerprint #pregnancy test https://goo.gl/h1...
1    finally a transparant silicon case ^^ thanks t...
2    we love this! would you go? #talk #makememorie...
3    i'm wired i know i'm george i was made that wa...
4    what amazing service! apple won't even talk to...
Name: tweet, dtype: str

Remove links

In [20]:
data["tweet"] = data['tweet'].apply(lambda x: " ".join(re.sub(r'^https?:\/\/.*[\r\n]*', '', x, flags=re.MULTILINE) for x in x.split()))

In [21]:
data["tweet"].head(5)

0    #fingerprint #pregnancy test  #android #apps #...
1    finally a transparant silicon case ^^ thanks t...
2    we love this! would you go? #talk #makememorie...
3    i'm wired i know i'm george i was made that wa...
4    what amazing service! apple won't even talk to...
Name: tweet, dtype: str

Remove punctuations

In [22]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [23]:
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

data["tweet"] = data["tweet"].apply(remove_punctuations)

In [26]:
data["tweet"].head(5)

0    fingerprint pregnancy test  android apps beaut...
1    finally a transparant silicon case  thanks to ...
2    we love this would you go talk makememories un...
3    im wired i know im george i was made that way ...
4    what amazing service apple wont even talk to m...
Name: tweet, dtype: str

Remove numbers

In [27]:
data["tweet"] = data['tweet'].str.replace('\d+', '', regex=True)

In [28]:
data["tweet"].tail(10)

7910    perfect match instagood applewatch red instagr...
7911    i am completely in love with the new iphone em...
7912    tune in turn on drop out  gtd in one app  mobi...
7913    ok so my galaxy crashed after one day now i ha...
7914    gain followers rt this must follow me i follow...
7915    live out loud lol liveoutloud selfie smile son...
7916    we would like to wish you an amazing day make ...
7917    helping my lovely  year old neighbor with her ...
7918    finally got my smart pocket wifi stay connecte...
7919    apple barcelona apple store bcn barcelona trav...
Name: tweet, dtype: str

Remove stopwords

In [37]:
import sys
print(sys.executable)

C:\Users\Asus\AppData\Local\Programs\Python\Python311\python.exe

In [38]:
import sys
!{sys.executable} -m pip install nltk

Collecting nltk
  Using cached nltk-3.9.3-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.2.19-cp311-cp311-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.5 kB ? eta -:--:--
     --------- ------------------------------ 10.2/41.5 kB ? eta -:--:--
     ---------------------------- --------- 30.7/41.5 kB 259.2 kB/s eta 0:00:01
     -------------------------------------  41.0/41.5 kB 279.3 kB/s eta 0:00:01
     -------------------------------------- 41.5/41.5 kB 199.0 kB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from click->nltk) (0.4.6)
Using cached nltk-3.9.3-py3-none-any.whl (1.5 MB)
Downloading regex-2026.2.19-cp311-cp311-win_amd64.whl (277 kB)
   ---------------------------------------- 0.0/277.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/277.9 kB ? eta -:--:--
   ---- ----------------------------------- 30.7/277.9 kB 1.3 MB/s eta 0:00:01
   -------- ------------------------------ 61.4/277.9 kB 544.7 kB/s eta 0:00:01
   ---------- ---------------------------- 71.7/277.9 kB 435.7 kB/s eta 0:00:01
   ------------ -------------------------- 92.2/277.9 kB 476.3 kB/s eta 0:00:01
   --------------- ---------------------- 112.6/277.9 kB 504.4 kB/s eta 0:00:01
   --------------- ---------------------- 112.6/277.9 kB 504.4 kB/s eta 0:00:01
   --------------- ---------------------- 112.6/277.9 kB 504.4 kB/s eta 0:00:01
   ---------------- --------------------- 122.9/277.9 kB 343.4 kB/s eta 0:00:01
   ------------------- ------------------ 143.4/277.9 kB 340.5 kB/s eta 0:00:01
   --------------------- ---------------- 153.6/277.9 kB 353.1 kB/s eta 0:00:01
   ----------------------- -------------- 174.1/277.9 kB 337.8 kB/s eta 0:00:01
   ------------------------- ------------ 184.3/277.9 kB 327.8 kB/s eta 0:00:01
   ---------------------------- --------- 204.8/277.9 kB 355.7 kB/s eta 0:00:01
   ------------------------------ ------- 225.3/277.9 kB 352.5 kB/s eta 0:00:01
   ----------------------------------- -- 256.0/277.9 kB 383.4 kB/s eta 0:00:01
   -------------------------------------- 277.9/277.9 kB 380.7 kB/s eta 0:00:00
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Installing collected packages: regex, joblib, click, nltk
Successfully installed click-8.3.1 joblib-1.5.3 nltk-3.9.3 regex-2026.2.19

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\Asus\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [39]:
import nltk

In [40]:
nltk.download('stopwords', download_dir='../static/model')

[nltk_data] Downloading package stopwords to ../static/model...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [41]:
with open('../static/model/corpora/stopwords/english', 'r') as file:
    sw = file.read().splitlines()

In [42]:
sw

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [43]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(x for x in x.split() if x not in sw))

In [44]:
data["tweet"].head()

0    fingerprint pregnancy test android apps beauti...
1    finally transparant silicon case thanks uncle ...
2    love would go talk makememories unplug relax i...
3    im wired know im george made way iphone cute d...
4    amazing service apple wont even talk question ...
Name: tweet, dtype: str

Stemming

In [45]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [46]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(ps.stem(x) for x in x.split()))

In [47]:
data["tweet"].head()

0    fingerprint pregnanc test android app beauti c...
1    final transpar silicon case thank uncl yay son...
2    love would go talk makememori unplug relax iph...
3    im wire know im georg made way iphon cute dave...
4    amaz servic appl wont even talk question unles...
Name: tweet, dtype: str

In [48]:
 data

        id  label                                              tweet
0        1      0  fingerprint pregnanc test android app beauti c...
1        2      0  final transpar silicon case thank uncl yay son...
2        3      0  love would go talk makememori unplug relax iph...
3        4      0  im wire know im georg made way iphon cute dave...
4        5      1  amaz servic appl wont even talk question unles...
...    ...    ...                                                ...
7915  7916      0  live loud lol liveoutloud selfi smile soni mus...
7916  7917      0  would like wish amaz day make everi minut coun...
7917  7918      0  help love year old neighbor ipad morn made rea...
7918  7919      0  final got smart pocket wifi stay connect anyti...
7919  7920      0  appl barcelona appl store bcn barcelona travel...

[7920 rows x 3 columns]

### Building Vacabulary

In [49]:
from collections import Counter
vocab = Counter()

In [50]:
vocab

Counter()

In [51]:
for sentence in data['tweet']:
    vocab.update(sentence.split())

In [52]:
len(vocab)

15949

In [53]:
data.shape

(7920, 3)

In [54]:
tokens = [key for key in vocab if vocab[key] > 10]

In [55]:
tokens

['test',
 'android',
 'app',
 'beauti',
 'cute',
 'health',
 'iger',
 'iphoneonli',
 'iphonesia',
 'iphon',
 'final',
 'case',
 'thank',
 'yay',
 'soni',
 'xperia',
 'love',
 'would',
 'go',
 'talk',
 'relax',
 'smartphon',
 'wifi',
 'connect',
 'im',
 'know',
 'made',
 'way',
 'home',
 'amaz',
 'servic',
 'appl',
 'wont',
 'even',
 'question',
 'pay',
 'stupid',
 'support',
 'softwar',
 'updat',
 'fuck',
 'phone',
 'big',
 'time',
 'happi',
 'us',
 'instap',
 'instadaili',
 'xperiaz',
 'new',
 'type',
 'c',
 'charger',
 'cabl',
 'uk',
 '…',
 'amazon',
 'year',
 'newyear',
 'start',
 'technolog',
 'samsunggalaxi',
 'iphonex',
 'shop',
 'listen',
 'music',
 'likeforlik',
 'photo',
 'fun',
 'selfi',
 'water',
 'camera',
 'picoftheday',
 'sun',
 'instagood',
 'boy',
 'outdoor',
 'hey',
 'make',
 'ipod',
 'dont',
 'color',
 'inch',
 'crash',
 'everi',
 'need',
 'realli',
 'drop',
 'ball',
 'design',
 'give',
 'anoth',
 'crazi',
 'purchas',
 'lol',
 'work',
 'hard',
 'play',
 'ipad',
 'batteri',
 'charg',
 'dead',
 'saturday',
 'summer',
 'like',
 'share',
 'want',
 'instagram',
 'photooftheday',
 'tweegram',
 'reason',
 'one',
 'suck',
 'truth',
 'agre',
 'fact',
 'store',
 'screen',
 'monday',
 'ur',
 'art',
 'easter',
 'dear',
 'friend',
 'face',
 'email',
 'seem',
 'pie',
 'wife',
 'ive',
 'day',
 'button',
 'back',
 'broke',
 'hit',
 'goe',
 'complet',
 'black',
 'keep',
 'get',
 'text',
 'cant',
 'check',
 'wallpap',
 'wall',
 'galaxi',
 'samsung',
 'patent',
 'million',
 'parti',
 'mess',
 'havent',
 'done',
 'noth',
 'touch',
 'lose',
 'pic',
 'kill',
 'someon',
 'hateappl',
 'flower',
 'green',
 'must',
 'watch',
 'youtub',
 'subscrib',
 'daili',
 'vlog',
 'twitch',
 'game',
 'ps',
 'xbox',
 'io',
 'live',
 'laugh',
 'life',
 'food',
 'instago',
 'instahub',
 'instagram…',
 'friendship',
 'dog',
 'famili',
 'goal',
 'bestfriend',
 'america',
 'taken',
 'sunset',
 'sky',
 'sister',
 'bought',
 'earli',
 'bday',
 'gift',
 'receiv',
 'note',
 'mani',
 'market',
 'delet',
 'song',
 'itun',
 'freak',
 'window',
 'advanc',
 'custom',
 'stand',
 'bad',
 'cheap',
 'tech',
 'bull',
 'smile',
 'creat',
 'let',
 'sunday',
 'alway',
 'eye',
 'ootd',
 'fashion',
 'blackandwhit',
 'film',
 'set',
 'video',
 'produc',
 'follow',
 'movi',
 'act',
 'pink',
 'sweet',
 'sexi',
 'ladi',
 'week',
 'end',
 'iphoneplu',
 'moment',
 'see',
 'differ',
 'photographi',
 'natur',
 'landscap',
 'view',
 'tree',
 'travel',
 'googl',
 'cut',
 'program',
 'look',
 'got',
 'christma',
 'girl',
 'instacool',
 'free',
 'appstor',
 'joy',
 'peac',
 'reflect',
 'rememb',
 'cloud',
 'gr',
 'iphone…',
 'babi',
 'pet',
 'news',
 'fail',
 'funni',
 'hate',
 'tablet',
 'person',
 'use',
 'fan',
 'think',
 'product',
 'friday',
 'call',
 'blackfriday',
 'holiday',
 'newyork',
 'busi',
 'money',
 'birthday',
 'tv',
 'comput',
 'school',
 'serious',
 'month',
 'good',
 'job',
 'actual',
 '£',
 'replac',
 'that',
 'still',
 'rt',
 'droid',
 'cool',
 'pictur',
 'l',
 'run',
 'beach',
 'sport',
 'bit',
 'hashtag',
 'yet',
 'arriv',
 'gain',
 'everyon',
 'sougofollow',
 'ff',
 'iphoneographi',
 'iphonephotographi',
 'mobil',
 'bright',
 'user',
 'date',
 'less',
 'random',
 'instamood',
 'wine',
 'creativ',
 'hot',
 'icon',
 'origin',
 'pop',
 'red',
 'rock',
 'soul',
 'singer',
 'univers',
 'wed',
 'thought',
 'id',
 'lost',
 'ipadmini',
 'feel',
 'broken',
 'light',
 'pleas',
 'indonesia',
 'gold',
 'potd',
 'reset',
 'sorri',
 'white',
 'tea',
 'chill',
 'cover',
 'g',
 'came',
 'magic',
 'come',
 'followsunday',
 'followback',
 'teamfollowback',
 'retweet',
 'ya',
 'thing',
 'i’m',
 'it’',
 'alreadi',
 'problem',
 'issu',
 'abl',
 'sonya',
 'shoot',
 'put',
 'price',
 'devic',
 'win',
 'box',
 'memori',
 'brother',
 '–',
 'oh',
 'lip',
 'enjoy',
 'playstat',
 'gamer',
 'someth',
 'wrong',
 'right',
 'today',
 'earphon',
 'lifestyl',
 'fuckyou',
 'never',
 'bug',
 'littl',
 'qualiti',
 'girlfriend',
 'card',
 'z',
 'present',
 'mom',
 'macbookpro',
 'macbook',
 'quot',
 'word',
 'tweetgram',
 'great',
 'repair',
 'hour',
 'everyth',
 'mode',
 'usa',
 'compani',
 'model',
 'cd',
 'featur',
 'didnt',
 'coffe',
 'effect',
 'spring',
 'galaxynot',
 'special',
 'valentin',
 'nowplay',
 'daughter',
 'poem',
 'car',
 'sign',
 'lunch',
 'park',
 'banana',
 'autumn',
 'spend',
 'much',
 'book',
 'say',
 'u',
 'took',
 'download',
 'ad',
 'twitter',
 'educ',
 'n',
 'miss',
 'last',
 'min',
 'tmobil',
 'rid',
 'absolut',
 'annoy',
 'level',
 'buy',
 'full',
 'version',
 'import',
 'mood',
 'blog',
 'style',
 'bestoftheday',
 'pretti',
 'babe',
 'send',
 'turn',
 'imessag',
 'sleep',
 'popular',
 'tweet',
 'shotoniphon',
 'photograph',
 'sync',
 'second',
 'fml',
 'candi',
 'nice',
 'wait',
 'hand',
 'gb',
 'first',
 'bar',
 'key',
 'long',
 'cold',
 'boot',
 'siri',
 'doesnt',
 'liter',
 'cri',
 'contact',
 'wonder',
 'avail',
 'b',
 'laptop',
 'vaio',
 'blackberri',
 'best',
 'fruit',
 'fall',
 'soon',
 'yum',
 'mac',
 'display',
 'told',
 'stop',
 'p',
 'three',
 'ship',
 'gear',
 'well',
 'past',
 'singl',
 'capetownsup',
 'sup',
 'surf',
 'capetown',
 'pro',
 'half',
 'stuff',
 'excit',
 'open',
 'mine',
 'piss',
 'offici',
 'keyboard',
 'okay',
 'though',
 'enough',
 'simpl',
 'th',
 'refus',
 'night',
 'son',
 'instagood…',
 'jj',
 'makeup',
 'valentinesday',
 'februari',
 'portrait',
 'shot',
 'sonyalpha',
 'mm',
 'password',
 'zoom',
 'stevejob',
 'yall',
 'addict',
 'prophet',
 'husband',
 'kindl',
 'a…',
 'upgrad',
 'help',
 'children',
 'there',
 'least',
 'tab',
 'real',
 'visit',
 'hi',
 'world',
 'old',
 'followm',
 'likelik',
 'samsung…',
 'swag',
 'cat',
 'edit',
 'sick',
 'paint',
 'bullshit',
 'may',
 'perfect',
 'instaphoto',
 'welcom',
 'draw',
 'os',
 'throw',
 'fast',
 'w',
 'take',
 'two',
 'next',
 'offer',
 'middl',
 'access',
 'account',
 'find',
 'citi',
 'stori',
 'destini',
 'awesom',
 'accessori',
 'info',
 'goodnight',
 'dream',
 'hope',
 'uae',
 'lucki',
 'deal',
 'passion',
 'read',
 'edm',
 'whole',
 'playlist',
 'god',
 'nx',
 'cuti',
 'high',
 'usb',
 'geek',
 'bot',
 'gadget',
 'power',
 'pc',
 'sprint',
 'pick',
 'wish',
 'minut',
 'count',
 'tl',
 'drive',
 'nyc',
 'gay',
 'readi',
 'cellphon',
 'space',
 'ny',
 'tattoo',
 'total',
 'ye',
 'via',
 'air',
 'instal',
 'fit',
 'plu',
 'sim',
 'florida',
 'sale',
 'nokia',
 'motorola',
 'lg',
 'without',
 'hold',
 'speed',
 'unitedst',
 'guitarplay',
 'smart',
 'crap',
 'calendar',
 'event',
 'icloud',
 'angri',
 'bird',
 'freez',
 'ever',
 'sinc',
 'team',
 'tri',
 'convers',
 'wouldnt',
 'small',
 'blue',
 '—',
 'steemit',
 'sonylen',
 'len',
 'sonyphotographi',
 'imag',
 'photofe',
 'feed',
 'yeah',
 'gorgeou',
 'ig',
 'orang',
 'haha',
 'dress',
 'lock',
 'speaker',
 'reallyr',
 'colleg',
 'true',
 'chocol',
 'shit',
 'ador',
 'nofilt',
 'drink',
 'purpl',
 'tasti',
 'garden',
 'андроид',
 'guy',
 'bestpric',
 'jun',
 'unlock',
 'caus',
 'manag',
 'mommi',
 'bless',
 'could',
 'chines',
 'close',
 'system',
 'morn',
 'nike',
 'goodmorn',
 'r',
 'imac',
 'sell',
 'mad',
 'purpos',
 'pari',
 'answer',
 'roll',
 'verizon',
 'headphon',
 'show',
 'sound',
 'itali',
 'socialmedia',
 'learn',
 'smoke',
 'tomorrow',
 'here',
 'delici',
 'far',
 'away',
 'ebay',
 'fix',
 'easi',
 'silver',
 'oneplu',
 'provid',
 'experi',
 'flag',
 'emoji',
 'chang',
 'al',
 'april',
 'man',
 'wanna',
 'your',
 'tell',
 'kid',
 'backup',
 'peopl',
 'dad',
 'anyon',
 'els',
 'block',
 'number',
 'possibl',
 'frustrat',
 'file',
 'bro',
 'rhyme',
 'thx',
 'jailbreak',
 'sit',
 'restor',
 'stock',
 'mother',
 'igdaili',
 'marri',
 'healthi',
 'ugh',
 'x',
 'bc',
 'gratitud',
 'edg',
 'unbox',
 'wow',
 'sonyphoto',
 'top',
 'phonecas',
 'june',
 'sad',
 'yellow',
 'woman',
 'might',
 'india',
 'canada',
 'europ',
 'super',
 'care',
 'map',
 'applestor',
 'hello',
 'order',
 'sent',
 'went',
 'wasnt',
 'insta',
 'newphon',
 'fish',
 'london',
 'vsco',
 'track',
 'catch',
 'finger',
 'anymor',
 'captur',
 'futur',
 'cell',
 'instalik',
 'sony…',
 'march',
 'proud',
 'hateiphon',
 'sticker',
 'vscocam',
 'bring',
 'better',
 'kiss',
 'heart',
 'fresh',
 'librari',
 'inspir',
 'inlov',
 'luxuri',
 'exquisit',
 'squishi',
 'charm',
 'strap',
 'toy',
 'decor',
 'cake',
 'theyr',
 'lte',
 'facebook',
 'wipe',
 'human',
 'bff',
 'instalov',
 'storag',
 'wake',
 'shitti',
 'wast',
 'switch',
 'blond',
 'load',
 'sue',
 'teamandroid',
 'da',
 'ly',
 'lion',
 'steve',
 'also',
 'ill',
 'osx',
 'photoshoot',
 'coupl',
 'favorit',
 'forc',
 'newtoy',
 'nascar',
 'tire',
 'appar',
 'ago',
 'zeeland',
 'appletv',
 'ask',
 'said',
 'meet',
 'electron',
 'gener',
 'link',
 'code',
 'tshirt',
 'tbt',
 'beat',
 'screw',
 'videogam',
 'motiv',
 'sunni',
 'nikon',
 'useless',
 'boyfriend',
 'weekend',
 'cook',
 'japan',
 'starbuck',
 'almost',
 'cousin',
 'tag',
 'applesuck',
 'bye',
 'search',
 'dinner',
 'discount',
 'cheer',
 'bluetooth',
 'wireless',
 'data',
 'spent',
 'puppi',
 'vacat',
 'anim',
 'notebook',
 'redbubbl',
 'iphonecas',
 'king',
 'yo',
 'left',
 'mean',
 'what',
 'yesterday',
 'mayb',
 'trump',
 'california',
 'repost',
 'samsungmobil',
 'gone',
 'social',
 'break',
 'trip',
 'slow',
 'rain',
 'wtf',
 'anyth',
 'cuz',
 'hd',
 'microsoft',
 'applewatch',
 'duo',
 'dj',
 'save',
 'mr',
 'releas',
 'gonna',
 'entir',
 'part',
 'die',
 'k',
 'tip',
 'gotta',
 'eat',
 'walk',
 'side',
 'explor',
 'hous',
 'room',
 'rs',
 'piano',
 'v',
 'thankyou',
 'happen',
 'page',
 'surpris',
 'deliveri',
 'messag',
 'vocat',
 'thailand',
 'khaoko',
 'ilc',
 'snapspeed…',
 'merri',
 'htc',
 'onlin',
 'psn',
 'flash',
 '•',
 'treat',
 'tagsforlik',
 'cost',
 'crack',
 'collect',
 'stuck',
 'planet',
 'men',
 'followfollow',
 'blow',
 'latest',
 'consol',
 'blogger',
 'protect',
 'skin',
 'choos',
 'uniqu',
 'piec',
 'lot',
 'remov',
 'secur',
 'princess',
 'mind',
 'becom',
 'miami',
 'nail',
 'rip',
 'figur',
 'network',
 'bitch',
 'tuesday',
 'f',
 'idea',
 'fb',
 'omg',
 'innov',
 'player',
 'forev',
 'satisfi',
 'tonight',
 'artist',
 'sing',
 'click',
 'hair',
 'ride',
 'leav',
 'colour',
 'togeth',
 'asshol',
 ...]

In [56]:
def save_vocabulary(lines, filename):
    data = '\n'.join(lines)
    file = open(filename, 'w', encoding="utf-8")
    file.write(data)
    file.close()

save_vocabulary(tokens, '../static/model/vocabulary.txt')

### Divide dataset

In [57]:
X = data['tweet']
y = data['label']

In [61]:
import sys
!{sys.executable} -m pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 650.1 kB/s eta 0:00:00
Requirement already satisfied: joblib>=1.3.0 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/36.6 MB 1.3 MB/s eta 0:00:28
   ---------------------------------------- 0.1/36.6 MB 1.2 MB/s eta 0:00:30
   ---------------------------------------- 0.2/36.6 MB 1.1 MB/s eta 0:00:34
   ---------------------------------------- 0.2/36.6 MB 986.4 kB/s eta 0:00:37
   ---------------------------------------- 0.3/36.6 MB 927.4 kB/s eta 0:00:40
   ---------------------------------------- 0.3/36.6 MB 951.8 kB/s eta 0:00:39
   ---------------------------------------- 0.3/36.6 MB 941.3 kB/s eta 0:00:39
   ---------------------------------------- 0.4/36.6 MB 1.0 MB/s eta 0:00:36
    --------------------------------------- 0.5/36.6 MB 1.0 MB/s eta 0:00:36
    --------------------------------------- 0.5/36.6 MB 983.0 kB/s eta 0:00:37
    --------------------------------------- 0.5/36.6 MB 983.5 kB/s eta 0:00:37
    --------------------------------------- 0.6/36.6 MB 983.9 kB/s eta 0:00:37
    --------------------------------------- 0.6/36.6 MB 966.7 kB/s eta 0:00:38
    --------------------------------------- 0.6/36.6 MB 976.0 kB/s eta 0:00:37
    --------------------------------------- 0.7/36.6 MB 946.8 kB/s eta 0:00:38
    --------------------------------------- 0.7/36.6 MB 946.8 kB/s eta 0:00:38
    --------------------------------------- 0.7/36.6 MB 946.8 kB/s eta 0:00:38
    --------------------------------------- 0.7/36.6 MB 946.8 kB/s eta 0:00:38
    --------------------------------------- 0.7/36.6 MB 946.8 kB/s eta 0:00:38
    --------------------------------------- 0.7/36.6 MB 946.8 kB/s eta 0:00:38
    --------------------------------------- 0.7/36.6 MB 741.4 kB/s eta 0:00:49
    --------------------------------------- 0.9/36.6 MB 895.0 kB/s eta 0:00:40
   - -------------------------------------- 0.9/36.6 MB 877.4 kB/s eta 0:00:41
   - -------------------------------------- 1.0/36.6 MB 883.4 kB/s eta 0:00:41
   - -------------------------------------- 1.0/36.6 MB 873.8 kB/s eta 0:00:41
   - -------------------------------------- 1.0/36.6 MB 859.2 kB/s eta 0:00:42
   - -------------------------------------- 1.0/36.6 MB 859.7 kB/s eta 0:00:42
   - -------------------------------------- 1.1/36.6 MB 852.0 kB/s eta 0:00:42
   - -------------------------------------- 1.1/36.6 MB 860.6 kB/s eta 0:00:42
   - -------------------------------------- 1.2/36.6 MB 861.6 kB/s eta 0:00:42
   - -------------------------------------- 1.3/36.6 MB 906.1 kB/s eta 0:00:39
   - -------------------------------------- 1.3/36.6 MB 909.1 kB/s eta 0:00:39
   - -------------------------------------- 1.4/36.6 MB 948.9 kB/s eta 0:00:38
   - -------------------------------------- 1.4/36.6 MB 948.9 kB/s eta 0:00:38
   - -------------------------------------- 1.6/36.6 MB 977.1 kB/s eta 0:00:36
   - -------------------------------------- 1.6/36.6 MB 964.1 kB/s eta 0:00:37
   - -------------------------------------- 1.6/36.6 MB 958.5 kB/s eta 0:00:37
   - -------------------------------------- 1.7/36.6 MB 977.5 kB/s eta 0:00:36
   - -------------------------------------- 1.8/36.6 MB 1.0 MB/s eta 0:00:35
   -- ------------------------------------- 1.8/36.6 MB 1.0 MB/s eta 0:00:35
   -- ------------------------------------- 2.0/36.6 MB 1.0 MB/s eta 0:00:34
   -- ------------------------------------- 2.0/36.6 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.1/36.6 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.1/36.6 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.1/36.6 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.1/36.6 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.3/36.6 MB 1.1 MB/s eta 0:00:32
   -- ------------------------------------- 2.4/36.6 MB 1.1 MB/s eta 0:00:31
   -- ------------------------------------- 2.4/36.6 MB 1.1 MB/s eta 0:00:31
   -- ------------------------------------- 2.5/36.6 MB 1.1 MB/s eta 0:00:32
   -- ------------------------------------- 2.5/36.6 MB 1.1 MB/s eta 0:00:32
   -- ------------------------------------- 2.5/36.6 MB 1.1 MB/s eta 0:00:32
   -- ------------------------------------- 2.5/36.6 MB 1.0 MB/s eta 0:00:33
   -- ------------------------------------- 2.6/36.6 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.6/36.6 MB 1.0 MB/s eta 0:00:33
   -- ------------------------------------- 2.7/36.6 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.7/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 2.8/36.6 MB 1.1 MB/s eta 0:00:32
   --- ------------------------------------ 2.9/36.6 MB 1.1 MB/s eta 0:00:32
   --- ------------------------------------ 2.9/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.0/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.0/36.6 MB 1.1 MB/s eta 0:00:32
   --- ------------------------------------ 3.0/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.1/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.1/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.2/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.2/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.3/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.3/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.3/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.4/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.4/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.4/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.5/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.5/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.5/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.6/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.6/36.6 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/36.6 MB 1.0 MB/s eta 0:00:33
   ---- ----------------------------------- 3.7/36.6 MB 1.0 MB/s eta 0:00:33
   ---- ----------------------------------- 3.8/36.6 MB 1.0 MB/s eta 0:00:33
   ---- ----------------------------------- 3.9/36.6 MB 1.0 MB/s eta 0:00:33
   ---- ----------------------------------- 3.9/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.0/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.1/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.1/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.1/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.2/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.2/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.2/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.3/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.3/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.4/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.4/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.4/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.5/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.5/36.6 MB 1.0 MB/s eta 0:00:32
   ---- ----------------------------------- 4.5/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.6/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.6/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.7/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.7/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.8/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.8/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.8/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 4.9/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.0/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.0/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.0/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.1/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.2/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.2/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.3/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.3/36.6 MB 1.0 MB/s eta 0:00:32
   ----- ---------------------------------- 5.4/36.6 MB 1.0 MB/s eta 0:00:31
   ----- ---------------------------------- 5.4/36.6 MB 1.0 MB/s eta 0:00:31
   ----- ---------------------------------- 5.4/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.5/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.5/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.5/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.5/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.7/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.7/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.8/36.6 MB 1.0 MB/s eta 0:00:31
   ------ --------------------------------- 5.8/36.6 MB 999.8 kB/s eta 0:00:31
   ------ --------------------------------- 5.8/36.6 MB 998.0 kB/s eta 0:00:31
   ------ --------------------------------- 5.9/36.6 MB 996.2 kB/s eta 0:00:31
   ------ --------------------------------- 5.9/36.6 MB 995.2 kB/s eta 0:00:31
   ------ --------------------------------- 6.0/36.6 MB 998.6 kB/s eta 0:00:31
   ------ --------------------------------- 6.0/36.6 MB 993.3 kB/s eta 0:00:31
   ------ --------------------------------- 6.0/36.6 MB 988.2 kB/s eta 0:00:31
   ------ --------------------------------- 6.1/36.6 MB 986.4 kB/s eta 0:00:31
   ------ --------------------------------- 6.1/36.6 MB 982.2 kB/s eta 0:00:32
   ------ --------------------------------- 6.1/36.6 MB 979.9 kB/s eta 0:00:32
   ------ --------------------------------- 6.2/36.6 MB 978.2 kB/s eta 0:00:32
   ------ --------------------------------- 6.2/36.6 MB 975.0 kB/s eta 0:00:32
   ------ --------------------------------- 6.2/36.6 MB 974.3 kB/s eta 0:00:32
   ------ --------------------------------- 6.2/36.6 MB 971.1 kB/s eta 0:00:32
   ------ --------------------------------- 6.3/36.6 MB 968.9 kB/s eta 0:00:32
   ------ --------------------------------- 6.3/36.6 MB 967.4 kB/s eta 0:00:32
   ------ --------------------------------- 6.4/36.6 MB 966.1 kB/s eta 0:00:32
   ------ --------------------------------- 6.4/36.6 MB 966.8 kB/s eta 0:00:32
   ------ --------------------------------- 6.4/36.6 MB 966.8 kB/s eta 0:00:32
   ------- -------------------------------- 6.4/36.6 MB 953.4 kB/s eta 0:00:32
   ------- -------------------------------- 6.5/36.6 MB 951.4 kB/s eta 0:00:32
   ------- -------------------------------- 6.5/36.6 MB 947.8 kB/s eta 0:00:32
   ------- -------------------------------- 6.5/36.6 MB 945.8 kB/s eta 0:00:32
   ------- -------------------------------- 6.5/36.6 MB 941.8 kB/s eta 0:00:32
   ------- -------------------------------- 6.6/36.6 MB 940.5 kB/s eta 0:00:32
   ------- -------------------------------- 6.6/36.6 MB 936.5 kB/s eta 0:00:33
   ------- -------------------------------- 6.6/36.6 MB 931.7 kB/s eta 0:00:33
   ------- -------------------------------- 6.6/36.6 MB 928.4 kB/s eta 0:00:33
   ------- -------------------------------- 6.6/36.6 MB 927.3 kB/s eta 0:00:33
   ------- -------------------------------- 6.7/36.6 MB 925.5 kB/s eta 0:00:33
   ------- -------------------------------- 6.7/36.6 MB 923.7 kB/s eta 0:00:33
   ------- -------------------------------- 6.7/36.6 MB 920.6 kB/s eta 0:00:33
   ------- -------------------------------- 6.7/36.6 MB 918.1 kB/s eta 0:00:33
   ------- -------------------------------- 6.8/36.6 MB 915.0 kB/s eta 0:00:33
   ------- -------------------------------- 6.8/36.6 MB 910.6 kB/s eta 0:00:33
   ------- -------------------------------- 6.8/36.6 MB 907.7 kB/s eta 0:00:33
   ------- -------------------------------- 6.8/36.6 MB 904.2 kB/s eta 0:00:33
   ------- -------------------------------- 6.8/36.6 MB 901.3 kB/s eta 0:00:34
   ------- -------------------------------- 6.9/36.6 MB 898.0 kB/s eta 0:00:34
   ------- -------------------------------- 6.9/36.6 MB 898.8 kB/s eta 0:00:34
   ------- -------------------------------- 6.9/36.6 MB 893.7 kB/s eta 0:00:34
   ------- -------------------------------- 6.9/36.6 MB 891.5 kB/s eta 0:00:34
   ------- -------------------------------- 7.0/36.6 MB 890.4 kB/s eta 0:00:34
   ------- -------------------------------- 7.0/36.6 MB 890.4 kB/s eta 0:00:34
   ------- -------------------------------- 7.0/36.6 MB 890.4 kB/s eta 0:00:34
   ------- -------------------------------- 7.0/36.6 MB 890.4 kB/s eta 0:00:34
   ------- -------------------------------- 7.0/36.6 MB 890.4 kB/s eta 0:00:34
   ------- -------------------------------- 7.1/36.6 MB 877.7 kB/s eta 0:00:34
   ------- -------------------------------- 7.1/36.6 MB 877.7 kB/s eta 0:00:34
   ------- -------------------------------- 7.1/36.6 MB 871.3 kB/s eta 0:00:34
   ------- -------------------------------- 7.1/36.6 MB 870.5 kB/s eta 0:00:34
   ------- -------------------------------- 7.2/36.6 MB 867.6 kB/s eta 0:00:34
   ------- -------------------------------- 7.2/36.6 MB 865.6 kB/s eta 0:00:34
   ------- -------------------------------- 7.2/36.6 MB 864.8 kB/s eta 0:00:35
   ------- -------------------------------- 7.2/36.6 MB 862.0 kB/s eta 0:00:35
   ------- -------------------------------- 7.2/36.6 MB 861.3 kB/s eta 0:00:35
   ------- -------------------------------- 7.3/36.6 MB 860.1 kB/s eta 0:00:35
   ------- -------------------------------- 7.3/36.6 MB 857.4 kB/s eta 0:00:35
   -------- ------------------------------- 7.3/36.6 MB 854.7 kB/s eta 0:00:35
   -------- ------------------------------- 7.4/36.6 MB 855.6 kB/s eta 0:00:35
   -------- ------------------------------- 7.4/36.6 MB 851.4 kB/s eta 0:00:35
   -------- ------------------------------- 7.4/36.6 MB 850.7 kB/s eta 0:00:35
   -------- ------------------------------- 7.5/36.6 MB 853.5 kB/s eta 0:00:35
   -------- ------------------------------- 7.5/36.6 MB 852.1 kB/s eta 0:00:35
   -------- ------------------------------- 7.5/36.6 MB 853.7 kB/s eta 0:00:35
   -------- ------------------------------- 7.6/36.6 MB 850.8 kB/s eta 0:00:35
   -------- ------------------------------- 7.6/36.6 MB 852.1 kB/s eta 0:00:34
   -------- ------------------------------- 7.7/36.6 MB 851.1 kB/s eta 0:00:35
   -------- ------------------------------- 7.7/36.6 MB 854.6 kB/s eta 0:00:34
   -------- ------------------------------- 7.8/36.6 MB 857.3 kB/s eta 0:00:34
   -------- ------------------------------- 7.8/36.6 MB 854.8 kB/s eta 0:00:34
   -------- ------------------------------- 7.8/36.6 MB 853.0 kB/s eta 0:00:34
   -------- ------------------------------- 7.8/36.6 MB 853.0 kB/s eta 0:00:34
   -------- ------------------------------- 7.9/36.6 MB 850.3 kB/s eta 0:00:34
   -------- ------------------------------- 7.9/36.6 MB 850.3 kB/s eta 0:00:34
   -------- ------------------------------- 7.9/36.6 MB 849.7 kB/s eta 0:00:34
   -------- ------------------------------- 8.0/36.6 MB 847.3 kB/s eta 0:00:34
   -------- ------------------------------- 8.0/36.6 MB 846.6 kB/s eta 0:00:34
   -------- ------------------------------- 8.0/36.6 MB 844.3 kB/s eta 0:00:34
   -------- ------------------------------- 8.0/36.6 MB 843.4 kB/s eta 0:00:34
   -------- ------------------------------- 8.1/36.6 MB 842.8 kB/s eta 0:00:34
   -------- ------------------------------- 8.1/36.6 MB 839.7 kB/s eta 0:00:34
   -------- ------------------------------- 8.1/36.6 MB 836.4 kB/s eta 0:00:35
   -------- ------------------------------- 8.1/36.6 MB 835.6 kB/s eta 0:00:35
   -------- ------------------------------- 8.2/36.6 MB 833.4 kB/s eta 0:00:35
   -------- ------------------------------- 8.2/36.6 MB 832.3 kB/s eta 0:00:35
   -------- ------------------------------- 8.2/36.6 MB 834.0 kB/s eta 0:00:35
   --------- ------------------------------ 8.3/36.6 MB 833.9 kB/s eta 0:00:34
   --------- ------------------------------ 8.3/36.6 MB 832.8 kB/s eta 0:00:34
   --------- ------------------------------ 8.4/36.6 MB 834.3 kB/s eta 0:00:34
   --------- ------------------------------ 8.4/36.6 MB 832.7 kB/s eta 0:00:34
   --------- ------------------------------ 8.4/36.6 MB 832.7 kB/s eta 0:00:34
   --------- ------------------------------ 8.4/36.6 MB 832.1 kB/s eta 0:00:34
   --------- ------------------------------ 8.5/36.6 MB 827.8 kB/s eta 0:00:34
   --------- ------------------------------ 8.5/36.6 MB 828.5 kB/s eta 0:00:34
   --------- ------------------------------ 8.5/36.6 MB 826.2 kB/s eta 0:00:34
   --------- ------------------------------ 8.5/36.6 MB 826.2 kB/s eta 0:00:34
   --------- ------------------------------ 8.5/36.6 MB 822.2 kB/s eta 0:00:35
   --------- ------------------------------ 8.6/36.6 MB 820.2 kB/s eta 0:00:35
   --------- ------------------------------ 8.6/36.6 MB 817.2 kB/s eta 0:00:35
   --------- ------------------------------ 8.6/36.6 MB 815.5 kB/s eta 0:00:35
   --------- ------------------------------ 8.6/36.6 MB 813.0 kB/s eta 0:00:35
   --------- ------------------------------ 8.6/36.6 MB 810.1 kB/s eta 0:00:35
   --------- ------------------------------ 8.6/36.6 MB 810.1 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 805.9 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 805.9 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 803.1 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 800.6 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 797.9 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 797.9 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 794.3 kB/s eta 0:00:36
   --------- ------------------------------ 8.7/36.6 MB 794.3 kB/s eta 0:00:36
   --------- ------------------------------ 8.8/36.6 MB 791.6 kB/s eta 0:00:36
   --------- ------------------------------ 8.8/36.6 MB 790.2 kB/s eta 0:00:36
   --------- ------------------------------ 8.8/36.6 MB 786.6 kB/s eta 0:00:36
   --------- ------------------------------ 8.8/36.6 MB 784.1 kB/s eta 0:00:36
   --------- ------------------------------ 8.8/36.6 MB 784.1 kB/s eta 0:00:36

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\Asus\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train